### ISSUE TITLE
Luafilters: Remove the `c` or `content` property from unnecessary examples

### ISSUE THREAD

**Issue by MattDodsonEnglish** [IlonaSilverwood/pan-docs#2]
The `.c` field is obsolete since v2.15. Its appearance is unnecessary and creates ambiguity.
For example, it could be removed here.

```lua
function Strong(elem)
  return pandoc.Subscript(elem.c)
end
```

**Comment by MattDodsonEnglish** [comment]
To be investigated: should the content field removed from all these references? EG https://pandoc.org/lua-filters.html#pandoc.link

**Comment by MattDodsonEnglish** [comment]
Pandoc does seem to require using fields to access other elements. For example, the `text` field does seem to be necessary here 

```lua
function Str (str)
    str.text = string.upper(str.text)
    return str
end
```

**Comment by tarleb** [comment]
> should the content field removed from all these references?

No, because we need to be able to distinguish between the element and its contents. So, e.g., to convert strongly emphasized text to underlined text one would write

``` lua
function Strong (strong)
  return pandoc.Underlined(strong.content)
end
```

but to make it *both* strongly emphasized and underlined we would write

``` lua
function Strong (strong)
  return pandoc.Underlined(strong)
end
```

**Comment by MattDodsonEnglish** [comment]
> but to make it both strongly emphasized and underlined we would write

Oh, I'm glad you commented this, because I did not catch the distinction. I was thinking the _entire_ `.c` field was obsolete, not just the alias for content.

I put a small PR in.


https://github.com/jgm/pandoc/pull/8857
